/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.Item;
import Model.Acces;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 *@afri
 */
public class Accessories extends javax.swing.JInternalFrame {

    /**
     * Creates new form Acces
     */
    public Accessories() {
        initComponents();
        show_Item();
    }

    public ArrayList<Acces> ItemList() {
        ArrayList<Acces> ItemList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
            Statement st = con.createStatement();
            String query = "Select * from Acces order by Name";
            ResultSet rs = st.executeQuery(query);
            Acces item;
            while (rs.next()) {
                item = new Acces(rs.getString("ID"), rs.getString("Name"), rs.getString("Company"), rs.getInt("Quantity"), rs.getFloat("Price"), rs.getFloat("Sprice"));
                ItemList.add(item);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ItemList;
    }

    public void show_Item() {
        ArrayList<Acces> list = ItemList();
        DefaultTableModel model = (DefaultTableModel) tblAdd.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getID();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getCompany();
            row[3] = list.get(i).getQuantity();
            row[4] = list.get(i).getPrice();
            row[5] = list.get(i).getSprice();
            model.addRow(row);
        }
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdd = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnResetadd = new javax.swing.JButton();
        txtSales = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel5.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 124, -1));

        tblAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Company", "Quantity", "Price", "Sales Of Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdd.getTableHeader().setReorderingAllowed(false);
        tblAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAddMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAdd);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 563, 431));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Name");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 110, 55, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Id");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 74, 55, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Quantity");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 174, 55, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Price");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 210, 55, 25));

        txtId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel5.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 76, 91, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel5.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 112, 91, -1));

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel5.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 176, 74, -1));

        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel5.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 212, 91, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setText("Add");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel5.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 515, -1, -1));

        btnResetadd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnResetadd.setText("Reset");
        btnResetadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetaddActionPerformed(evt);
            }
        });
        jPanel5.add(btnResetadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 515, -1, -1));

        txtSales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel5.add(txtSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 248, 91, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Sales Of Price");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 246, 84, 25));

        txtCompany.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel5.add(txtCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 143, 91, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Company");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 141, 76, 25));

        btnUpdate1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 515, -1, -1));

        btnDelete1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 515, -1, -1));

        jLabel19.setText("Search");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 70, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 837, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        int YesORNo = JOptionPane.showConfirmDialog(null, "Do you want Delete", "Delete Option", JOptionPane.YES_NO_OPTION);
        if (YesORNo == 0) {
            try {
                int row = tblAdd.getSelectedRow();
                String value = (tblAdd.getModel().getValueAt(row, 0).toString());
                String ID = txtId.getText();
                String Name = txtName.getText();
                String Company = txtCompany.getText();
                int Quantity = Integer.parseInt(txtQuantity.getText());
                float Price = Float.parseFloat(txtPrice.getText());
                float Sprice = Float.parseFloat(txtSales.getText());
                Item items = new Item(ID, Name, Company, Quantity, Price, Sprice);

                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
                PreparedStatement pst;
                String query = "Delete from Acces Where ID = '" + items.getID() + "'";
                pst = con.prepareStatement(query);
                pst.executeUpdate();
                DefaultTableModel model2 = (DefaultTableModel) tblAdd.getModel();
                model2.setRowCount(0);
                show_Item();
                txtId.setText(null);
                txtName.setText(null);
                txtCompany.setText(null);
                txtPrice.setText(null);
                txtQuantity.setText(null);
                txtSales.setText(null);
                JOptionPane.showMessageDialog(null, "Successfully Delete ", "information", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Item ID is invalid ", "Error", JOptionPane.INFORMATION_MESSAGE);//
            }
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
        int YesORNo = JOptionPane.showConfirmDialog(null, "Do you want Update Data", "Update Option", JOptionPane.YES_NO_OPTION);
        if (YesORNo == 0) {
            try {
                int row = tblAdd.getSelectedRow();
                String value = (tblAdd.getModel().getValueAt(row, 0).toString());
                String ID = txtId.getText();
                String Name = txtName.getText();
                String Company = txtCompany.getText();
                int Quantity = Integer.parseInt(txtQuantity.getText());
                float Price = Float.parseFloat(txtPrice.getText());
                float Sprice = Float.parseFloat(txtSales.getText());
                Item items = new Item(ID, Name, Company, Quantity, Price, Sprice);

                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
                PreparedStatement pst;
                String query = "update Acces set ID = '" + items.getID() + "', Name = '" + items.getName() + "', Company = '" + items.getCompany() + "', Price = '" + items.getPrice() + "',Quantity = '" + items.getQuantity() + "' , Sprice = '" + items.getSprice() + "' where ID = '" + items.getID() + "'";
                pst = con.prepareStatement(query);
                pst.executeUpdate();
                DefaultTableModel model = (DefaultTableModel) tblAdd.getModel();
                model.setRowCount(0);
                show_Item();

                JOptionPane.showMessageDialog(null, "Successfully Update ", "information", JOptionPane.INFORMATION_MESSAGE);
                txtId.setText(null);
                txtName.setText(null);
                txtCompany.setText(null);
                txtPrice.setText(null);
                txtQuantity.setText(null);
                txtSales.setText(null);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);//"Item ID is invalid OR You can't change ID ", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnResetaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetaddActionPerformed
        // TODO add your handling code here:
        int YesORNo = JOptionPane.showConfirmDialog(null, "Do you want Clear All Data", "Clear Option", JOptionPane.YES_NO_OPTION);
        if (YesORNo == 0) {
            txtId.setText(null);
            txtName.setText(null);
            txtCompany.setText(null);
            txtPrice.setText(null);
            txtQuantity.setText(null);
            txtSales.setText(null);
        }
    }//GEN-LAST:event_btnResetaddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
            Statement st = con.createStatement();
            String query = "Insert into Acces (ID,Name,Company,Quantity,Price,Sprice) values (?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, txtId.getText());
            pst.setString(2, txtName.getText());
            pst.setString(3, txtCompany.getText());
            int Quantity = Integer.parseInt(txtQuantity.getText());
            pst.setInt(4, Quantity);
            float Price = Float.parseFloat(txtPrice.getText());
            pst.setFloat(5, Price);
            float Sprice = Float.parseFloat(txtSales.getText());
            pst.setFloat(6, Price);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) tblAdd.getModel();
            model.setRowCount(0);
            show_Item();
            JOptionPane.showMessageDialog(null, "Accessories Sucessfully Added!");
            txtId.setText(null);
            txtName.setText(null);
            txtCompany.setText(null);
            txtPrice.setText(null);
            txtQuantity.setText(null);
            txtSales.setText(null);
            // txtSearchName.setText(null);
            //txtaddSearch.setText(null);
            //txtaddSearchName.setText(null);

            //txtCategorySearch.setText(null);
            /* String Id = txtId.getText();
            String Name = txtName.getText();
            String Company = txtCompany.getText();
            int Quantity = Integer.parseInt(txtQuantity.getText());
            float Price = Float.parseFloat(txtPrice.getText());
            float Sprice = Float.parseFloat(txtSales.getText());

            Item myitem = new Item(Id,Name,Company,Quantity,Price,Sprice);
            itemServic service = new itemServic();
            service.addItem(myitem);*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Alredy Add Product! ,Check The Name", "Save Error", JOptionPane.ERROR_MESSAGE);//
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        ArrayList<Item> al = new ArrayList<Item>();
        //al = new ArrayList<AddItems>();
        String val = txtSearch.getText().toString().trim();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
            String query = "Select * from Acces where ID like '" + val + "%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Item item;
            while (rs.next()) {
                item = new Item(rs.getString("ID"), rs.getString("Name"), rs.getString("Company"), rs.getInt("Quantity"), rs.getFloat("Price"), rs.getFloat("Sprice"));
                al.add(item);
            }

            DefaultTableModel model = (DefaultTableModel) tblAdd.getModel();
            model.setRowCount(0);
            Object[] row = new Object[6];
            for (int i = 0; i < al.size(); i++) {
                row[0] = al.get(i).getID();
                row[1] = al.get(i).getName();
                row[2] = al.get(i).getCompany();
                row[3] = al.get(i).getQuantity();
                row[4] = al.get(i).getPrice();
                row[5] = al.get(i).getSprice();
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cannot find Item Name", "Search Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAddMouseClicked
        // TODO add your handling code here:
        int i = tblAdd.getSelectedRow();
        TableModel model = tblAdd.getModel();
        txtId.setText(model.getValueAt(i, 0).toString());
        txtName.setText(model.getValueAt(i, 1).toString());
        txtCompany.setText(model.getValueAt(i, 2).toString());
        txtQuantity.setText(model.getValueAt(i, 3).toString());
        txtPrice.setText(model.getValueAt(i, 4).toString());
        txtSales.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_tblAddMouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnResetadd;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAdd;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSales;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
