/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import Model.Item;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author aafri
 */
public class OrderInstruments extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrderInstruments
     */
    String from,

    /**
     * Creates new form OrderInstruments
     */
    to, 

    /**
     * Creates new form OrderInstruments
     */
    host, 

    /**
     * Creates new form OrderInstruments
     */
    sub, 

    /**
     * Creates new form OrderInstruments
     */
    content;
    
    public OrderInstruments() {
        initComponents();
        show_Item();
    }

    public ArrayList<Item> ItemList() {
        ArrayList<Item> ItemList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
            Statement st = con.createStatement();
            String query = "Select * from Item order by Name";
            ResultSet rs = st.executeQuery(query);
            Item item;
            while (rs.next()) {
                item = new Item(rs.getString("ID"), rs.getString("Name"), rs.getString("Company"), rs.getInt("Quantity"), rs.getFloat("Price"), rs.getFloat("Sprice"));
                ItemList.add(item);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ItemList;
    }

    public void show_Item() {
        ArrayList<Item> list = ItemList();
        DefaultTableModel model = (DefaultTableModel) tblitem.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getID();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getCompany();
            row[3] = list.get(i).getQuantity();
            row[4] = list.get(i).getPrice();
            row[5] = list.get(i).getSprice();
            model.addRow(row);
        }
    }

   public String sendMail1(String Email, String Password, String ToEmail, String Subject, String Text) {

        String Msg;

        final String username = Email;
        final String password = Password;

        Properties props = new Properties();
        props.put("mail.smtp.auth", true);
        props.put("mail.smtp.starttls.enable", true);
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.setProperty("mail.smtp.ssl.trust", "smtp.gmail.com");

        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(Email));//ur email
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(ToEmail));//u will send to
            message.setSubject(Subject);
            message.setText(Text);
            Transport.send(message);
            Msg = "true";
            return Msg;

        } catch (MessagingException ex) {
            return ex.toString();
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblitem = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtTotalAll = new javax.swing.JTextField();
        txtPay = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        btnSale = new javax.swing.JButton();
        txtNo = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        txtaddress = new javax.swing.JTextField();
        btnMail = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 151, -1));

        tblitem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Company", "Quantity", "Price", "Sales Of Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblitem.getTableHeader().setReorderingAllowed(false);
        tblitem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblitemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblitem);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 619, 231));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 112, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 112, -1));

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
        });
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 74, -1));

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 88, -1));

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 88, -1));

        txtTotalAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAllActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 110, -1));

        txtPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayActionPerformed(evt);
            }
        });
        txtPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPayKeyPressed(evt);
            }
        });
        jPanel1.add(txtPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 110, -1));

        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 110, -1));

        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSales.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblSales);
        if (tblSales.getColumnModel().getColumnCount() > 0) {
            tblSales.getColumnModel().getColumn(0).setResizable(false);
            tblSales.getColumnModel().getColumn(1).setResizable(false);
            tblSales.getColumnModel().getColumn(2).setResizable(false);
            tblSales.getColumnModel().getColumn(3).setResizable(false);
            tblSales.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 619, 200));

        btnSale.setText("Sale");
        btnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleActionPerformed(evt);
            }
        });
        jPanel1.add(btnSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, -1));

        txtNo.setText("0");
        txtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 50, -1));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, -1, -1));

        txtBill.setColumns(20);
        txtBill.setRows(5);
        jScrollPane3.setViewportView(txtBill);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 120));
        jPanel1.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 210, -1));

        btnMail.setText("Send Mail");
        btnMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMailActionPerformed(evt);
            }
        });
        jPanel1.add(btnMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, -1, -1));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, -1, -1));

        jLabel1.setText("Balance");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 50, 20));

        jLabel2.setText("Search");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 50, 20));

        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 40, 20));

        jLabel4.setText("Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 30, 20));

        jLabel5.setText("Quantity");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 50, 20));

        jLabel6.setText("Total");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 40, 20));

        jLabel7.setText("Item No.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 50, 20));

        jLabel8.setText("Total All");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 50, 20));

        jLabel9.setText("Pay");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 40, 20));

        jLabel10.setText("Mail");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 30, 20));

        jLabel11.setText("ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        setBounds(0, 0, 837, 607);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtTotalAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAllActionPerformed

    private void txtPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayActionPerformed

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceActionPerformed

    private void tblitemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblitemMouseClicked
        // TODO add your handling code here:
        int i = tblitem.getSelectedRow();
        TableModel model = tblitem.getModel();
        txtId.setText(model.getValueAt(i, 0).toString());
        txtName.setText(model.getValueAt(i, 1).toString());
        txtPrice.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_tblitemMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        ArrayList<Item> al = new ArrayList<Item>();
        //al = new ArrayList<AddItems>();
        String val = txtSearch.getText().toString().trim();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
            String query = "Select * from Item where ID like '" + val + "%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Item item;
            while (rs.next()) {
                item = new Item(rs.getString("ID"), rs.getString("Name"), rs.getString("Company"), rs.getInt("Quantity"), rs.getFloat("Price"), rs.getFloat("Sprice"));
                al.add(item);
            }

            DefaultTableModel model = (DefaultTableModel) tblitem.getModel();
            model.setRowCount(0);
            Object[] row = new Object[6];
            for (int i = 0; i < al.size(); i++) {
                row[0] = al.get(i).getID();
                row[1] = al.get(i).getName();
                row[2] = al.get(i).getCompany();
                row[3] = al.get(i).getQuantity();
                row[4] = al.get(i).getPrice();
                row[5] = al.get(i).getSprice();
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cannot find Item Name", "Search Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        // TODO add your handling code here:
        float Price = Float.parseFloat(txtPrice.getText());
        int Qty = Integer.parseInt(txtQuantity.getText());
        float tot = Qty * Price;
        txtTotal.setText(String.valueOf(tot));
    }//GEN-LAST:event_txtQuantityKeyPressed

    private void btnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleActionPerformed
        // TODO add your handling code here:
        //Sale
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblSales.getModel();
        model.addRow(new Object[]{
            txtId.getText(),
            txtName.getText(),
            txtPrice.getText(),
            txtQuantity.getText(),
            txtTotal.getText(),});
        float sum = 0;
        int j = 0;
        //double Discount = 0.0;
        for (int i = 0; i < tblSales.getRowCount(); i++) {
            //Discount = Discount + (Double.parseDouble(tblSales.getValueAt(i, 4).toString()));//* (Double.parseDouble(jTableBill.getValueAt(i, 1).toString()) * Double.parseDouble(jTableBill.getValueAt(i, 2).toString())
            sum = sum + Float.parseFloat(tblSales.getValueAt(i, 4).toString());
            j = i + 1;
        }
        txtTotalAll.setText(String.valueOf(sum));
        txtNo.setText(String.valueOf(j));
        txtId.setText("");
        txtName.setText("");
        txtQuantity.setText("");
        txtPrice.setText("");
        txtTotal.setText("");
    }//GEN-LAST:event_btnSaleActionPerformed

    private void txtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoActionPerformed

    private void txtPayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayKeyPressed
        // TODO add your handling code here:
        float Pay = Float.parseFloat(txtPay.getText());
        float tot = Float.parseFloat(txtTotalAll.getText());
        float tall = Pay - tot;
        txtBalance.setText(String.valueOf(tall));
    }//GEN-LAST:event_txtPayKeyPressed

    public void Print() {

        float Total2 = Float.parseFloat(txtTotalAll.getText());
        float Pay = Float.parseFloat(txtPay.getText());
        float Balance = Float.parseFloat(txtBalance.getText());
        //int BillNo = Integer.parseInt(txtBillNo.getText());
        String ID = "";
        String Name = "";
        float Price = (float) 0.0;
        int Quantity = (int) 0.0;
        float Total = (float) 0.0;

        txtBill.setText(txtBill.getText() + "            Your Order Has Been Completed. Thank You!!              \n");
        txtBill.setText(txtBill.getText() + "\n");

        txtBill.setText(txtBill.getText() + "****************************************************************************\n");
        txtBill.setText(txtBill.getText() + "             WELCOME TO Music Mart             \n");
        txtBill.setText(txtBill.getText() + "****************************************************************************\n");

        txtBill.setText(txtBill.getText() + "\n");
        txtBill.setText(txtBill.getText() + "Item ID" + "\t" + "Item Name" + "\t" + " Price " + "\t" + "Quantity" + "\t" + " Amount " + "\n");
        txtBill.setText(txtBill.getText() + "------------------------------------------------------------------------------------------------\n");

        //int Count = 0;
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblSales.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            ID = (String) model.getValueAt(i, 0);
            Name = (String) model.getValueAt(i, 1);
            Price = (Float.parseFloat(model.getValueAt(i, 2).toString()));
            Quantity = (Integer.parseInt(model.getValueAt(i, 3).toString()));
            Total = (Float.parseFloat(model.getValueAt(i, 4).toString()));
            txtBill.setText(txtBill.getText() + ID + "\t" + Name + "\t" + Price + "\t" + Quantity + "\t" + Total + "\n");
            //  Count = Count + 1;
        }

        txtBill.setText(txtBill.getText() + "\n");

        //txtBill.setText(txtBill.getText() +"\t"+"Bill No  :  "+Count+"\n");
        txtBill.setText(txtBill.getText() + "\t" + "Total Bill" + "  :  " + " Rs." + (new DecimalFormat("0.00").format(Total2)) + "\n");
        txtBill.setText(txtBill.getText() + "\t" + "Payment" + "  :  " + " Rs." + (new DecimalFormat("0.00").format(Pay)) + "\n");
        txtBill.setText(txtBill.getText() + "\t" + "Balance" + "  :  " + " Rs." + (new DecimalFormat("0.00").format(Balance)) + "\n");
        //txtBill.setText(txtBill.getText() + "\n");//All  grugs
        txtBill.setText(txtBill.getText() + "****************************************************************************\n");
        txtBill.setText(txtBill.getText() + "\t" + "            Thank You Come Again\n");
        txtBill.setText(txtBill.getText() + "****************************************************************************\n");
        txtBill.setText(txtBill.getText() + "                             " + "System by Group \n");
    }

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
            String ID = "";
            String Name = "";
            float Price = (float) 0.0;
            int Quantity = (int) 0.0;
            float Total = (float) 0.0;

            for (int i = 0; i < tblSales.getRowCount(); i++) {
                ID = (String) tblSales.getValueAt(i, 0);
                Name = (String) tblSales.getValueAt(i, 1);
                Price = (Float.parseFloat(tblSales.getValueAt(i, 2).toString()));
                Quantity = (Integer.parseInt(tblSales.getValueAt(i, 3).toString()));
                Total = (Float.parseFloat(tblSales.getValueAt(i, 4).toString()));

                try {
                    String query2 = "Insert into Report (TDate,ID,Name,Price,Quantity,Total) values (CURDATE(),?,?,?,?,?)";
                    PreparedStatement pst2 = con.prepareStatement(query2);
                    pst2.setString(1, ID);
                    pst2.setString(2, Name);
                    pst2.setFloat(3, Price);
                    pst2.setInt(4, Quantity);
                    pst2.setFloat(5, Total);
                    pst2.executeUpdate();

                    try {
                        String query3 = "Update Item set Quantity = Quantity - '" + Quantity + "' where ID = '" + ID + "'";
                        PreparedStatement pst3 = con.prepareStatement(query3);
                        pst3.executeUpdate();
                        DefaultTableModel model2 = (DefaultTableModel) tblSales.getModel();
                        model2.setRowCount(0);
                        DefaultTableModel model1 = (DefaultTableModel) tblitem.getModel();
                        model1.setRowCount(0);
                        show_Item();
                        Print();
                        txtTotalAll.setText("");
                        txtPay.setText("");
                        txtBalance.setText("");
                        txtNo.setText("0");
                        //JOptionPane.showMessageDialog(null, "Qty Updsted");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMailActionPerformed
        // TODO add your handling code here:
        try {
            String email = "mohamedafri@gmail.com";
            String password = "blahblahblah";
            String Toemail = txtaddress.getText();
            host = "localhost:8080";
            String subject = "Regarding Music Mart Order";
            String message = txtBill.getText();

            String data = new OrderInstruments().sendMail1(email, password, Toemail, subject, message);
            System.out.println(data);

            if (data.equals("true")) {
                JOptionPane.showMessageDialog(this, "EMAIL WAS SENT SUCCESSFULLY");
            } else {
                JOptionPane.showMessageDialog(this, "ERROR IN SENDING EMAIL");
            }

            txtaddress.setText("");
            txtBill.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "e");
        }
    }//GEN-LAST:event_btnMailActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtaddress.setText("");
        txtBill.setText("");
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMail;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblSales;
    private javax.swing.JTable tblitem;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextArea txtBill;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtPay;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalAll;
    private javax.swing.JTextField txtaddress;
    // End of variables declaration//GEN-END:variables
}
