/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.ReqRepire;
import Model.Repire;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author afri
 */
public class Settings extends javax.swing.JInternalFrame {

    /**
     * Creates new form Seetings
     */
    public Settings() {
        initComponents();
        show_Repire();
        show_ReqRepire();
    }

    public ArrayList<Repire> RepireList() {
        ArrayList<Repire> RepireList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
            Statement st = con.createStatement();
            String query = "Select * from addrepire order by Name";
            ResultSet rs = st.executeQuery(query);
            Repire item;
            while (rs.next()) {
                item = new Repire(rs.getString("Name"), rs.getString("ID"), rs.getString("Gmail"), rs.getString("Address"), rs.getInt("Telephone"));
                RepireList.add(item);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return RepireList;
    }

    public void show_Repire() {
        ArrayList<Repire> list = RepireList();
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getName();
            row[1] = list.get(i).getId();
            row[2] = list.get(i).getGmail();
            row[3] = list.get(i).getAddress();
            row[4] = list.get(i).getTelephone();
            model.addRow(row);
        }
    }

    public ArrayList<ReqRepire> ReqRepireList() {
        ArrayList<ReqRepire> ReqRepireList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
            Statement st = con.createStatement();
            String query = "Select * from reqrepire order by Name";
            ResultSet rs = st.executeQuery(query);
            ReqRepire item;
            while (rs.next()) {
                item = new ReqRepire(rs.getString("Name"), rs.getString("ID"), rs.getString("Gmail"), rs.getString("Address"), rs.getInt("Telephone"));
                ReqRepireList.add(item);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ReqRepireList;
    }

    public void show_ReqRepire() {
        ArrayList<ReqRepire> list = ReqRepireList();
        DefaultTableModel model = (DefaultTableModel) tblView1.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getName();
            row[1] = list.get(i).getId();
            row[2] = list.get(i).getGmail();
            row[3] = list.get(i).getAddress();
            row[4] = list.get(i).getTelephone();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnRest = new javax.swing.JButton();
        txtCode = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNameupd = new javax.swing.JTextField();
        txtPasswordupd = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtRest = new javax.swing.JButton();
        txtChangePsw = new javax.swing.JButton();
        txtPasswordnewupd = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtPasswordcon = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        txtTele = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAdrress = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtGmail = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNameview = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        txtReset = new javax.swing.JButton();
        txtCodeview = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblView1 = new javax.swing.JTable();
        txtTelerepire = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAdrressRepire = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtGmailRepire = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNameRepire = new javax.swing.JTextField();
        btnAddRepirre = new javax.swing.JButton();
        txtReset1 = new javax.swing.JButton();
        txtCodeRepire = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        txtIdRepire = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnRemove1 = new javax.swing.JButton();

        setClosable(true);

        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Code");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("User Id");

        txtName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        btnAdd.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRest.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnRest.setText("Reset");
        btnRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestActionPerformed(evt);
            }
        });

        txtCode.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCode)
                            .addComponent(txtPassword)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRest)
                        .addGap(41, 41, 41)
                        .addComponent(btnAdd)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnRest))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add User", jPanel2);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("User Id");

        txtNameupd.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        txtPasswordupd.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Password");

        txtRest.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtRest.setText("Reset");
        txtRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRestActionPerformed(evt);
            }
        });

        txtChangePsw.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtChangePsw.setText("Change Password");
        txtChangePsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChangePswActionPerformed(evt);
            }
        });

        txtPasswordnewupd.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("New Password");

        txtPasswordcon.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Confirm Password");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtRest)
                                .addGap(41, 41, 41)
                                .addComponent(txtChangePsw))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPasswordnewupd)
                                    .addComponent(txtPasswordupd)
                                    .addComponent(txtNameupd, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtPasswordcon, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNameupd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPasswordupd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPasswordnewupd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPasswordcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChangePsw)
                    .addComponent(txtRest))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Change Password", jPanel3);

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Id", "Gmail", "Address", "Telephone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblView.getTableHeader().setReorderingAllowed(false);
        tblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblView);
        if (tblView.getColumnModel().getColumnCount() > 0) {
            tblView.getColumnModel().getColumn(0).setResizable(false);
            tblView.getColumnModel().getColumn(1).setResizable(false);
            tblView.getColumnModel().getColumn(2).setResizable(false);
            tblView.getColumnModel().getColumn(3).setResizable(false);
            tblView.getColumnModel().getColumn(4).setResizable(false);
        }

        txtTele.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Telephone");

        txtAdrress.setColumns(20);
        txtAdrress.setRows(5);
        jScrollPane2.setViewportView(txtAdrress);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Addrress");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setText("Gmail");

        txtGmail.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        txtId.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("ID");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setText("Name");

        txtNameview.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNameview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameviewActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        txtReset.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtReset.setText("Reset");
        txtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResetActionPerformed(evt);
            }
        });

        txtCodeview.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setText("Code");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTele, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtGmail)
                                .addComponent(txtNameview)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(60, 60, 60)
                        .addComponent(txtCodeview, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtNameview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodeview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRemove)))
                        .addGap(18, 18, 18)
                        .addComponent(txtReset)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Repire", jPanel4);

        tblView1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Id", "Gmail", "Address", "Telephone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblView1.getTableHeader().setReorderingAllowed(false);
        tblView1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblView1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblView1);
        if (tblView1.getColumnModel().getColumnCount() > 0) {
            tblView1.getColumnModel().getColumn(0).setResizable(false);
            tblView1.getColumnModel().getColumn(1).setResizable(false);
            tblView1.getColumnModel().getColumn(2).setResizable(false);
            tblView1.getColumnModel().getColumn(3).setResizable(false);
            tblView1.getColumnModel().getColumn(4).setResizable(false);
        }

        txtTelerepire.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel14.setText("Telephone");

        txtAdrressRepire.setColumns(20);
        txtAdrressRepire.setRows(5);
        jScrollPane4.setViewportView(txtAdrressRepire);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel15.setText("Addrress");

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel16.setText("Gmail");

        txtGmailRepire.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel18.setText("Name");

        txtNameRepire.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtNameRepire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameRepireActionPerformed(evt);
            }
        });

        btnAddRepirre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnAddRepirre.setText("Add Repire");
        btnAddRepirre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRepirreActionPerformed(evt);
            }
        });

        txtReset1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtReset1.setText("Reset");
        txtReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReset1ActionPerformed(evt);
            }
        });

        txtCodeRepire.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel19.setText("Code");

        txtIdRepire.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtIdRepire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdRepireActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel20.setText("ID");

        btnRemove1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnRemove1.setText("Remove");
        btnRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18)
                        .addComponent(jLabel16)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(39, 39, 39))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(27, 27, 27)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelerepire, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGmailRepire, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(96, 96, 96)
                                    .addComponent(txtIdRepire, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(txtNameRepire, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(60, 60, 60)
                            .addComponent(txtCodeRepire, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnRemove1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddRepirre))))
                    .addComponent(txtReset1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtNameRepire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtIdRepire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGmailRepire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtTelerepire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodeRepire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddRepirre)))
                        .addGap(9, 9, 9)
                        .addComponent(btnRemove1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReset1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Request Repire", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 837, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestActionPerformed
        // TODO add your handling code here:
        txtCode.setText("");
        txtName.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnRestActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
            Statement st = con.createStatement();
// Statement st = con.createStatement();
            String query = "Insert into Login (ID,Password) values (?,?)";;
            //ResultSet rs = st.executeQuery(query);
            PreparedStatement pst = con.prepareStatement(query);
            String code = txtCode.getText();
            if (code.contains("12345")) {
                pst.setString(1, txtName.getText());
                pst.setString(2, txtPassword.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "New Employe Added");
                txtCode.setText("");
                txtName.setText("");
                txtPassword.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Your Code is INVALID");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtChangePswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChangePswActionPerformed
        // TODO add your handling code here:
        int YesORNo = JOptionPane.showConfirmDialog(null, "Do you want Update Data", "Update Option", JOptionPane.YES_NO_OPTION);
        if (YesORNo == 0) {
            try {
                String Name = txtNameupd.getText();
                String Password = txtPasswordupd.getText();
                String newPassword = txtPasswordnewupd.getText();
                String conPassword = txtPasswordcon.getText();
                if (newPassword.equalsIgnoreCase(conPassword)) {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
                    PreparedStatement pst;
                    String query = "update login set ID = '" + Name + "', Password = '" + newPassword + "' where ID = '" + Name + "'";
                    pst = con.prepareStatement(query);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Successfully Update ", "information", JOptionPane.INFORMATION_MESSAGE);
                    txtNameupd.setText("");
                    txtPassword.setText("");
                    txtPasswordcon.setText("");
                    txtPasswordnewupd.setText("");
                    txtPasswordupd.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "New Password not match with Confirm Pasword ");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);//"Item ID is invalid OR You can't change ID ", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtChangePswActionPerformed

    private void txtRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRestActionPerformed
        // TODO add your handling code here:
        txtNameupd.setText("");
        txtPassword.setText("");
        txtPasswordcon.setText("");
        txtPasswordnewupd.setText("");
        txtPasswordupd.setText("");
    }//GEN-LAST:event_txtRestActionPerformed

    private void txtNameviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameviewActionPerformed

    private void tblViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewMouseClicked
        // TODO add your handling code here:
        int i = tblView.getSelectedRow();
        TableModel model = tblView.getModel();
        txtNameview.setText(model.getValueAt(i, 0).toString());
        txtId.setText(model.getValueAt(i, 1).toString());
        txtGmail.setText(model.getValueAt(i, 2).toString());
        txtAdrress.setText(model.getValueAt(i, 3).toString());
        txtTele.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_tblViewMouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        String code = txtCodeview.getText();
        if (code.contains("12345")) {
            int YesORNo = JOptionPane.showConfirmDialog(null, "Do you want Delete", "Delete Option", JOptionPane.YES_NO_OPTION);
            if (YesORNo == 0) {
                try {
                    int row = tblView.getSelectedRow();
                    String value = (tblView.getModel().getValueAt(row, 0).toString());
                    String Name = txtNameview.getText();
                    String ID = txtId.getText();
                    String Gmail = txtGmail.getText();
                    String Address = txtAdrress.getText();
                    int Tele = Integer.parseInt(txtTele.getText());
                    Repire items = new Repire(Name, ID, Gmail, Address, Tele);

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
                    PreparedStatement pst;
                    String query = "Delete from addrepire Where ID = '" + items.getId() + "'";
                    pst = con.prepareStatement(query);
                    pst.executeUpdate();
                    DefaultTableModel model = (DefaultTableModel) tblView.getModel();
                    model.setRowCount(0);
                    show_Repire();
                    txtId.setText(null);
                    txtNameview.setText(null);
                    txtAdrress.setText(null);
                    txtTele.setText(null);
                    txtGmail.setText(null);
                    txtCodeview.setText(null);
                    JOptionPane.showMessageDialog(null, "Successfully Delete ", "information", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Item ID is invalid ", "Error", JOptionPane.INFORMATION_MESSAGE);//
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Invalide Code");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResetActionPerformed
        // TODO add your handling code here:
        txtId.setText(null);
        txtNameview.setText(null);
        txtAdrress.setText(null);
        txtTele.setText(null);
        txtGmail.setText(null);
        txtCodeview.setText(null);
    }//GEN-LAST:event_txtResetActionPerformed

    private void tblView1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblView1MouseClicked
        // TODO add your handling code here:
        int i = tblView1.getSelectedRow();
        TableModel model = tblView1.getModel();
        txtNameRepire.setText(model.getValueAt(i, 0).toString());
        txtIdRepire.setText(model.getValueAt(i, 1).toString());
        txtGmailRepire.setText(model.getValueAt(i, 2).toString());
        txtAdrressRepire.setText(model.getValueAt(i, 3).toString());
        txtTelerepire.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_tblView1MouseClicked

    private void txtNameRepireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameRepireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameRepireActionPerformed

    private void btnAddRepirreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRepirreActionPerformed
        // TODO add your handling code here:
        try {
            int row = tblView1.getSelectedRow();
            String value = (tblView1.getModel().getValueAt(row, 0).toString());
            String Name = txtNameRepire.getText();
            String ID = txtIdRepire.getText();
            String Gmail = txtGmailRepire.getText();
            String Address = txtAdrressRepire.getText();
            int Tele = Integer.parseInt(txtTelerepire.getText());
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
            Statement st = con.createStatement();
// Statement st = con.createStatement();
            String query = "Insert into addrepire (Name,ID,Gmail,Address,Telephone) values (?,?,?,?,?)";;
            //ResultSet rs = st.executeQuery(query);
            PreparedStatement pst = con.prepareStatement(query);
            String code = txtCodeRepire.getText();
            if (code.contains("12345")) {
                pst.setString(1, txtNameRepire.getText());
                pst.setString(2, txtIdRepire.getText());
                pst.setString(3, txtGmailRepire.getText());
                pst.setString(4, txtAdrressRepire.getText());
                int tele = Integer.parseInt(txtTelerepire.getText());
                pst.setInt(5, tele);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Added");
                try {
                    Repire items = new Repire(Name, ID, Gmail, Address, Tele);

                    String query1 = "Delete from reqrepire Where ID = '" + items.getId() + "'";
                    PreparedStatement pst1 = con.prepareStatement(query1);
                    pst1.executeUpdate();
                    DefaultTableModel model = (DefaultTableModel) tblView1.getModel();
                    model.setRowCount(0);
                    show_ReqRepire();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Item ID is invalid ", "Error", JOptionPane.INFORMATION_MESSAGE);//
                }
                DefaultTableModel model = (DefaultTableModel) tblView1.getModel();
                model.setRowCount(0);
                show_ReqRepire();
                DefaultTableModel model1 = (DefaultTableModel) tblView.getModel();
                model1.setRowCount(0);
                show_Repire();
                txtCodeRepire.setText("");
                txtIdRepire.setText(null);
                txtNameRepire.setText(null);
                txtAdrressRepire.setText(null);
                txtGmailRepire.setText(null);
                txtTelerepire.setText(null);
            } else {
                JOptionPane.showMessageDialog(null, "Your Code is INVALID");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnAddRepirreActionPerformed

    private void txtReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReset1ActionPerformed
        // TODO add your handling code here:
        txtCodeRepire.setText("");
        txtIdRepire.setText(null);
        txtNameRepire.setText(null);
        txtAdrressRepire.setText(null);
        txtGmailRepire.setText(null);
        txtTelerepire.setText(null);
    }//GEN-LAST:event_txtReset1ActionPerformed

    private void txtIdRepireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdRepireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdRepireActionPerformed

    private void btnRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove1ActionPerformed
        // TODO add your handling code here:
        String code = txtCodeRepire.getText();
        if (code.contains("12345")) {
            int YesORNo = JOptionPane.showConfirmDialog(null, "Do you want Delete", "Delete Option", JOptionPane.YES_NO_OPTION);
            if (YesORNo == 0) {
                try {
                    int row = tblView1.getSelectedRow();
                    String value = (tblView1.getModel().getValueAt(row, 0).toString());
                    String Name = txtNameRepire.getText();
                    String ID = txtIdRepire.getText();
                    String Gmail = txtGmailRepire.getText();
                    String Address = txtAdrressRepire.getText();
                    int Tele = Integer.parseInt(txtTelerepire.getText());
                    Repire items = new Repire(Name, ID, Gmail, Address, Tele);

                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/xmusic", "root", "");
                    PreparedStatement pst;
                    String query = "Delete from reqrepire Where ID = '" + items.getId() + "'";
                    pst = con.prepareStatement(query);
                    pst.executeUpdate();
                    DefaultTableModel model = (DefaultTableModel) tblView1.getModel();
                    model.setRowCount(0);
                    show_ReqRepire();
                    txtCodeRepire.setText("");
                    txtIdRepire.setText(null);
                    txtNameRepire.setText(null);
                    txtAdrressRepire.setText(null);
                    txtGmailRepire.setText(null);
                    txtTelerepire.setText(null);
                    JOptionPane.showMessageDialog(null, "Successfully Delete ", "information", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Item ID is invalid ", "Error", JOptionPane.INFORMATION_MESSAGE);//
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Invalide Code");
        }
    }//GEN-LAST:event_btnRemove1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddRepirre;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRemove1;
    private javax.swing.JButton btnRest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblView;
    private javax.swing.JTable tblView1;
    private javax.swing.JTextArea txtAdrress;
    private javax.swing.JTextArea txtAdrressRepire;
    private javax.swing.JButton txtChangePsw;
    private javax.swing.JPasswordField txtCode;
    private javax.swing.JPasswordField txtCodeRepire;
    private javax.swing.JPasswordField txtCodeview;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtGmailRepire;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdRepire;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameRepire;
    private javax.swing.JTextField txtNameupd;
    private javax.swing.JTextField txtNameview;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordcon;
    private javax.swing.JPasswordField txtPasswordnewupd;
    private javax.swing.JPasswordField txtPasswordupd;
    private javax.swing.JButton txtReset;
    private javax.swing.JButton txtReset1;
    private javax.swing.JButton txtRest;
    private javax.swing.JTextField txtTele;
    private javax.swing.JTextField txtTelerepire;
    // End of variables declaration//GEN-END:variables
}
